### ISSUE TITLE
Gebruik van alt="image of {{name.first}}"

### ISSUE THREAD

**Issue by krijnhoetmer** [matth96/matth96.github.io#11]
Vergelijk dit met de volgende voorbeelden:

- `<a href="/">Link to Homepage</a>`
- `<h3>Heading about Me</h3>`
- `<title>Title: My Website</title>`

Hoe kan je `alt` attribuut beter?

**Comment by matth96** [comment]
Ik heb de image of verwijdert. Je hebt gelijk Het is heel dubbel op. Het is al een afbeelding.

**Comment by krijnhoetmer** [comment]
Ik zou waarschijnlijk zelfs helemaal het `alt` attribuut leeg laten, aangezien in een element daarnaast ook al de naam staat. Als je het `alt` attribuut laat voorlezen, krijg je dan vaak twee keer dezelfde informatie horen.
