### ISSUE TITLE
Feature detection in JS ontbreekt

### ISSUE THREAD

**Issue by krijnhoetmer** [matth96/matth96.github.io#12]
Wat bijvoorbeeld als `XMLHttpRequest` niet bestaat in je browser?

**Comment by matth96** [comment]
ik heb een feature detect voor de XMLHttpRequest gedaan. Hij valt nu terug op window.location. Wat goed gesport word. http://caniuse.com/#search=window.location 

 #e8d6a29

**Comment by krijnhoetmer** [comment]
Is het niet makkelijker om dat geval gewoon _helemaal niets_ te doen, en terug te vallen naar de normale werking? :) Don't over-engineer.
