### ISSUE TITLE
Semantische classnames

### ISSUE THREAD

**Issue by MicheleNL** [matth96/matth96.github.io#4]
Ik vond in de code oa. de volgende classes: class=”order-1”, class=”flex” Bekijk of dit wel de classnames zijn die je wil gebruiken. We streven altijd naar semantische, beschrijvende classnames ipv classnames die over de opmaak / layout gaan.

**Comment by matth96** [comment]
Thanks for the feedback. I should know..
I've fixed this issue in pull request 1534a4f
