### ISSUE TITLE
Gebruik van <a href="#">

### ISSUE THREAD

**Issue by krijnhoetmer** [matth96/matth96.github.io#9]
Vraag je bij het tikken van zo'n link (in dit geval `<a href="#" class="card-close">Close</a>`) altijd af “Wat als je deze link in een nieuw tab/scherm opent?”

Dus ook hierbij die vraag; is dit het juiste element op die plek, of kan dit netter? Of kun je het `href` attribuut wel nuttig maken daar?

**Comment by matth96** [comment]
Ik heb het aangepast het href artibute heb ik veranderd naar /. Hierdoor werkt hij ook op een nieuwe pagina. #7dd0bfd
